### ISSUE TITLE
5 Brains, not 4

### ISSUE THREAD

**Issue by danninemx** [mrdavidlaing/javascript-koans#52]
AboutObjects.js line 32 has an expected answer of "They are Pinky and the Brain Brain Brain Brain" -- with 4 iterations of the string "Brain".

The actual pseudo code is:

    var megalomaniac = {
      mastermind : "Brain",
      henchman: "Pinky",
      battleCry: function (noOfBrains) {
        return "They are " + this.henchman + " and the" +
          Array(noOfBrains + 1).join(" " + this.mastermind);
      }
    };

The problem in question was:

    var battleCry = megalomaniac.battleCry(4);

If we indeed pass 4 as noOfBrains, since the method adds 1 to noOfBrains before joining them, would the result not have 5 "Brain"?

**Comment by endrin** [comment]
No. Actually, Array(noOfBrains + 1) creates 5-element array of undefined which is then joined together with " Brain". As there are five elements there will be four joins.

**Comment by danninemx** [comment]
That makes sense. Thank you.
