### ISSUE TITLE
function body as a string test

### ISSUE THREAD

**Issue by chrisgillis** [mrdavidlaing/javascript-koans#9]
var multiply = function (a, b) {
      //An internal comment
      return a \* b;
    };
    var stupid = "function (a, b) { \
      return a \* b; \
      }"
    expect(multiply.toString()).toBe(stupid);

why doesn't that work? if i remove the '\' lien terminators it works but Firefox throws an unterminated string literal error.

**Comment by adrianhorning08** [comment]
Wouldn't this work as well?
"function(a, b) {"
      "// An internal comment"
      "return a * b;"
    "};"
